; PlatformIO project for M5Stack Cardputer - Geometry Dash
; Build & upload:  pio run -t upload
; Serial monitor:  pio device monitor

[env:cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

lib_deps =
    m5stack/M5Cardputer @ ^1.0.3
